repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3
        types: [python]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        types: [python]

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-docstrings, flake8-import-order]
        types: [python]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-python-dateutil, types-pyyaml]
        args: [--ignore-missing-imports, --disallow-untyped-defs, --strict-optional]
        types: [python]
        exclude: ^tests/
